### ISSUE TITLE
Create crash with AvailableCommandsPacket

### ISSUE THREAD

**Issue by Virvolta** [WaterdogPE/WaterdogPE#104]
19:50:29 [WARN ] Received violation from VirVoltaSurMC: PacketViolationWarningPacket(type=MALFORMED_PACKET, severity=TERMINATING_CONNECTION, packetCauseId=76, context=)

I have this error if in one of my command I put a Command Enum with an arg type string with in it the word "daymarble" in the array (ps I don't know why this word but I know that if I don't put it in it works fine

**Comment by Alemiz112** [comment]
Hi, can you please provide information what downstream server software do you use?

It seems to be caused by software using outdated command param type ids.

**Comment by Alemiz112** [comment]
The proxy itself isnt the issue. It injects correct command param types. The issue is that PocketMine uses outdated values and client doesnt like that.

You can disable proxy commands injection in order to prevent it - set `inject_proxy_commands` option to `false` in proxy config.

**Comment by Virvolta** [comment]
ok thanks, but is the PM4 version up to date for this ?

**Comment by Alemiz112** [comment]
PM3 and PM4 have similar network implementation, so this issue persists.
