### ISSUE TITLE
Bedrock Dedicated Server & Pocketmine Generation

### ISSUE THREAD

**Issue by IvanCraft623** [WaterdogPE/WaterdogPE#105]
# Information:
WaterdogPE| ProtocolI | Java | MCBE Software involved
--- | --- | --- | ---
1.1.0 | 440 | 11 | PM4 & BDS

# Description:
The blocks generated in the world are sent to the client in the wrong way, replacing each other.

For example, torches instead of being shown to the player as torches, are ladders (not are exactly what they are replaced for, it is an example).

![image](https://user-images.githubusercontent.com/57236932/123574512-98e25200-d795-11eb-9e17-ddfe34e3ee8c.png)
# How to reproduce:

**1.** Add 2 servers, one using Pocketmine and the other Bedrock Dedicated Server
**2.** Set either of the 2 servers to the first priority
**3.** Join the proxy server, apparently you can find everything "normal"
**4.** Transfer to the opposite server, you will notice that all blocks are buggy

# Notes
- I have only tested this with PM4 and BDS, I don't know if PM3 or any other software will get the same errors.

**Comment by Alemiz112** [comment]
Hello, transfers between BDS and any other software are not supported at the moment due to several factors that can not be changed by us.

**Comment by TobiasG-DE** [comment]
Can be closed, main issue for BDS support is #49
