### ISSUE TITLE
Cannot use WaterDogPE to join Java Server (Geyser).

### ISSUE THREAD

**Issue by DJelly4K** [WaterdogPE/WaterdogPE#106]
**Describe the bug**
I use the latest version of WaterDogPE, the latest version of PowerNukkit *(used to transfer to another server)* and the latest version of Geyser *(the java server is PaperSpigot 1.12.2, also added Floodgate)*. I change the configuration of Geyser to offline mode, and the java server is also offline mode, But when you join that server *(from Nukkit server to Paperspigot server)*, the system prompts: to join this server, please log in to your Xbox account. If I don't use WaterDogPE to join and enter the address directly, this problem won't appear. I think it's a problem with WaterDogPE.

**To Reproduce**
1. I downloaded the latest version of WaterDogPE(WD), PowerNukkit(PN), Geyser and Floodgate, also PaperSpigot 1.12.2(PS).
2. I added Geyser&Floodgate into PaperSpigot 1.12.2. They worked normally. Then I configured WD&PN.
3. I take PN as the main server and enter through WD. When I try to enter PS with WD command, it gives an error prompt: to join this server, please log in to your Xbox account. But it's normal for me to join PS directly.

**Expected behavior**
It can join Java Server normally through WaterDogPE

**Screenshots**
*Tips for joining Java Server (Only English part)
![image](https://user-images.githubusercontent.com/68630033/124358245-0688f500-dc52-11eb-9b71-a79f780744cd.png)

*Join java server through address*
![image](https://user-images.githubusercontent.com/68630033/124358674-f4a85180-dc53-11eb-9265-e14840ac4066.png)

**Platform**
1.Windows Server 2019
2.AdoptOpenJDK 11&16 (11 used to the Java Server, others used 16)
3.WaterDogPE 1.1.0 (github release version)
4.Geyser 1.4 (git-master-7ae27c7) & Viaversion 4.0.0 (1.12.2 => 1.17)

**Comment by Alemiz112** [comment]
I think the message - "please log in to your Xbox account" - tells it clearly. You haven't disabled XBOX auth on the downstream which reports that.

**Comment by DJelly4K** [comment]
> I think the message - "please log in to your Xbox account" - tells it clearly. You haven't disabled XBOX auth on the downstream which reports that.
I turned off Xbox auth on all servers, you mean…?

**Comment by Alemiz112** [comment]
You have probably configured it incorrectly somewhere.

**Comment by DJelly4K** [comment]
> I think the message - "please log in to your Xbox account" - tells it clearly. You haven't disabled XBOX auth on the downstream which reports that.

I turned off Xbox auth on all servers, you mean…?

**Comment by DJelly4K** [comment]
> You have probably configured it incorrectly somewhere.

I checked everything, but I didn't find out why

**Comment by DJelly4K** [comment]
> You have probably configured it incorrectly somewhere.

Now I opened online mode on the Java Server. But it still says about Xbox auth...
No matter whether I open genuine verification or not, it prompts like this. I'm sure that the genuine verification of java server is turned on, and the floodgate function of geyser plugin is also turned on
What can i do?

**Comment by DJelly4K** [comment]
> You have probably configured it incorrectly somewhere.

Geyser reported TIMED_OUT.
WaterDogPE reported connected&disconnected
