### ISSUE TITLE
Protocol: Enabled encryption seems to delay packet sending after client initialization

### ISSUE THREAD

**Issue by Alemiz112** [WaterdogPE/WaterdogPE#109]
After player joins initial server or transfers the game behavior seems laggy because of upstream not delivering packets to client. This usually persists for few seconds but can take up to one minute. 

Performing several experiments confirms that this can be affected by disabling encryption - decreases the delay or removes it completely. This bug can be reproduced only on some machines, weird, OS type doesn't affect it. It can be only reproduced when **nukkit**  is the downstream server.

Doing debug shows that the packets are not queued and the issue is not coming form `ProxyBatchBridge`. In fact, packets are passed from bridge without any thread blocking directly to `BedrockSession` using one of `sendWrapped()` methods. It doesn't matter whatever packets are reencoded. Encryption itself does not block thread or create any delay - about *0.2ms - 5ms*.

Encrypted buffer is passed down to RakNet level where I guess the issue is coming from - I have noticed that datagrams holding encrypted payload are not send because of increased NAK ratio. Therefore this issue could be related to #108

**Comment by Alemiz112** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Encryption seems to delay transfers](https://trello.com/c/P9CG2oCZ/54-encryption-seems-to-delay-transfers)

**Comment by belohnung** [comment]
i could also reproduce this with high packet frequency while logging in, caused by saplings in water

**Comment by TobiasG-DE** [comment]
Yeah it's reproducable, though we're still searching for the root cause. if you want, feel free to take part at the hunt

**Comment by belohnung** [comment]
Since i don't know what you tried before and what ways there are to reproduce, id probably only find out what you know already.
If you could provide me with what you already found out id be willing to help :)

**Comment by irrld** [comment]
Any progress?

**Comment by Alemiz112** [comment]
I have done some more investigation over the time and might have spotted few issues that may contribute on this issue. I will probably have another look during the next weekend.

**Comment by irrld** [comment]
![image](https://user-images.githubusercontent.com/23135761/143109204-8384286c-c0df-420c-968a-9925a6f4c51b.png)
I'm currently getting this errors when connecting to PowerNukkit Downstream with WaterdogPE from ProxyPass. Could be related?

**Comment by Alemiz112** [comment]
No, this is not related.

**Comment by Alemiz112** [comment]
This was caused by a bug in JVM, which was fixed in the latest builds. Therefore it is recommended to update to latest version of java.
