### ISSUE TITLE
Could not connect: Outdated server!

### ISSUE THREAD

**Issue by PleaseInsertNameHere** [WaterdogPE/WaterdogPE#111]
Hello there!

A lot of players (including me) are recieving the following message when joining via the proxy: `Could not connect: Outdated server!`. Only after restarting the game for a few times, they've been able to join.

I've also noticed another weird issue (may be related to this):
When querying our proxy, it sometimes shows "1.16.220 - 0 players" but it's actually "1.17.10 - ... players"

Why is it like that? How can I fix this? Am I the only one experiencing this issue?

We're using version 1.1.1 (1.17.10, protocol 448)

**Comment by belohnung** [comment]
Could it be that you have two instances of WaterdogPE running?

**Comment by PleaseInsertNameHere** [comment]
I don't think we have 2 proxy instances running on the same port.

**Comment by PleaseInsertNameHere** [comment]
Alright, thank you. We've just fixed the issue.
