### ISSUE TITLE
Can't join on my server.

### ISSUE THREAD

**Issue by felischmi2003** [WaterdogPE/WaterdogPE#112]
Hello,

today I have first time instal the WaterdogPE Server on my Ubuntu Root Server with one Nukkit Server.
I installed the server like the docs.
After the Start the Server I would join him, also can't join him...
In the Waterdog console is all clan no errors
In my Lobby server console is this error:
`15:46:05 [INFO ] edingjhdlive[/127.0.0.1:57306] hat sich ausgeloggt disconnectionScreen.notAuthenticated`

Can me Help everyone, please?

With best Regrads,
Felix Schmitt

P.S. Sorry for my bad Englisch, I come from Germany

**Comment by TobiasG-DE** [comment]
Make sure you disable xbox authentication on your downstream server (Nukkit/PM..)
