### ISSUE TITLE
PacketViolationWarningPacket -__-

### ISSUE THREAD

**Issue by Soulstarop** [WaterdogPE/WaterdogPE#113]
When I join the server and trying to break block or chat or sometime automatically disconnect my client and say this message in console 

15:02:19 [WARN ] Received violation from SouL YT7829: PacketViolationWarningPacket(type=MALFORMED_PACKET, severity=TERMINATING_CONNECTION, packetCauseId=117, context=)
15:02:19 [INFO ] [/103.199.182.157:64763|SouL YT7829] -> Upstream has disconnected
15:02:19 [INFO ] [/103.199.182.157:64763|SouL YT7829] -> Downstream [Hub] has disconnected

Please help me to fix :)

**Comment by TobiasG-DE** [comment]
Are you sending the ScriptCustomEventPacket at any point?

**Comment by Soulstarop** [comment]
I don't know what is that I have done normal setuping steps

**Comment by TobiasG-DE** [comment]
Do you have any plugins on your server?

**Comment by Soulstarop** [comment]
yeah so many did I have to setup server again?

**Comment by TobiasG-DE** [comment]
One of your plugins is sending an Invalid packet. This is not a proxy-related issue, try to figure out which plugin it is and remove / replace it.
