### ISSUE TITLE
Immobile player is able to move

### ISSUE THREAD

**Issue by KCodeYT** [WaterdogPE/WaterdogPE#145]
Immobile players are able to move when they are transfered to a server this is caused by the "We-dont-care" policy of the WaterdogPE maintainers.

Maintainer edit: Reported issue appears to be that the downstream server can set the player immobile before the PlayStatusPacket with PlayState PLAYER_SPAWNED is received, and WDPE will explicitly remove that immobile state again as per this line ([ConnectedDownstreamHandler.java#L87](https://github.com/WaterdogPE/WaterdogPE/blob/master/src/main/java/dev/waterdog/waterdogpe/network/downstream/ConnectedDownstreamHandler.java#L87)) and therefore immobile state might be out of sync between client and downstream server since the proxy cannot notify the downstream server of the changes.

**Comment by KCodeYT** [comment]
Jokes beside its caused by the injection of the immobile state of the player entity in the [ConnectedDownstreamHandler#L87](https://github.com/WaterdogPE/WaterdogPE/tree/master/src/main/java/dev/waterdog/waterdogpe/network/downstream/ConnectedDownstreamHandler.java#L87)

**Comment by EinBexiii** [comment]
> Immobile players are able to move when they are transfered to a server this is caused by the "We-dont-care" policy of the WaterdogPE maintainers.

Shouldn't the downstream server ensure that the player is not immobile when leaving?

**Comment by KCodeYT** [comment]
> Shouldn't the downstream server ensure that the player is not immobile when leaving?

Hmm no because the proxy has to safely change entity values and not if and when they want.

**Comment by TobiasG-DE** [comment]
You shouldn't set someone immobile across servers. If you want to do that, just set the player immobile again on join. I don't see why that wouldn't be possible.

**Comment by irrld** [comment]
Anyways, if you guys wanna merge the fix. https://github.com/WaterdogPE/WaterdogPE/pull/146

**Comment by Alemiz112** [comment]
I don't understand your problem at all. If you set player as immobile on one server and than expect it to stay immobile on another, than it isn't how it works. Because new server can not know whether player is immobile, it would cause desynchronization.

**Comment by irrld** [comment]
First of all this wasn't my problem, and my goal was not to synchronize between servers. My goal to keep what new connected downstream sent not the old one. Its nonsense to synchronize immobility between servers its their job.

**Comment by irrld** [comment]
Oh this was not my pr lol, i don't know what they meant with this issue.

**Comment by TobiasG-DE** [comment]
@KCodeYT I edited your initial message, can you check whether this is what you meant?

**Comment by KCodeYT** [comment]
I meant that a player which is on server 1 and I set him immobile on this server 1, but now he transfers to server 2 on this server the player is not immobile again (completly fine, because he is should only be immobile on server 1), but if he again transfers to server 1 he can still move (even if he is in an immobile state).

**Comment by KCodeYT** [comment]
And the proxy can notify the server by sending for example a PlayerMovePacket with fake data, but the server should react on that by resending the immobile state

**Comment by irrld** [comment]
@KCodeYT https://github.com/WaterdogPE/WaterdogPE/pull/146 test with this changes and let us know.

**Comment by Alemiz112** [comment]
> I meant that a player which is on server 1 and I set him immobile on this server 1, but now he transfers to server 2 on this server the player is not immobile again (completly fine, because he is should only be immobile on server 1), but if he again transfers to server 1 he can still move (even if he is in an immobile state).

Well that is expected because when player gets back to server 1, it is same situation as when he transfers to server 2. During transfer player is disconnected from old server and so when he is sent back server just sees him as new connection.

> And the proxy can notify the server by sending for example a PlayerMovePacket with fake data, the now server should react on that by resending the immobile state

This is not something we should really take care of. We can not and do not want enforce server software will be listening for any of extra proxy inputs.

**Comment by irrld** [comment]
> I meant that a player which is on server 1 and I set him immobile on this server 1, but now he transfers to server 2 on this server the player is not immobile again (completly fine, because he is should only be immobile on server 1), but if he again transfers to server 1 he can still move (even if he is in an immobile state).

Do you set player as immobile again when connecting to server 1 for the second time?

**Comment by KCodeYT** [comment]
> Do you set player as immobile again when connecting to server 1 for the second time?

Yes, I send the immobile state again but before the PlayStatusPacket with PlayState PLAYER_SPAWNED is received

**Comment by irrld** [comment]
Okay try with my changes, that should fix your problem. If that works let us know. I tested myself and it was working. But maybe i'm doing something different on downstream. I was setting player as immobile on PlayerLoginEvent.

**Comment by KCodeYT** [comment]
Fixed, thanks Alemiz!
