### ISSUE TITLE
A MOTD-message for each forced host

### ISSUE THREAD

**Issue by xxAROX** [WaterdogPE/WaterdogPE#147]
```diff
servers:
  lobby:
    address: 0.0.0.0:19133
    server_type: bedrock
+   fhost-motd: Lobby # never shown because not in 'listener -> forced_hosts'
  test:
    address: 0.0.0.0:19131
    server_type: bedrock
+   fhost-motd: TEST SERVER
listener:
  forced_hosts:
    test.domain.com: test
```
**or something like that**

___

On test.domain.com it should display `TEST SERVER` otherwise `§3WaterdogPE`

**Comment by TobiasG-DE** [comment]
If i recall correctly thats not possible. The forced host system relies on the data sent in the login keychain. The motd is returned before that packet is sent, so we can't know the address they request it over.

**Comment by xxAROX** [comment]
ahh okay
