### ISSUE TITLE
Too many players disconnected for timeout

### ISSUE THREAD

**Issue by ImHammer** [WaterdogPE/WaterdogPE#151]
I need help, the downstream is disconnecting all the players at once for the reason *timeout* and only when all the players come from the proxy (WaterdogPE), everything happens normally when there are 10 to 15 players inside the downstream, more when it passes 20 the downstream starts to disconnect many at once by timeout, OBS: not all will be disconnected.

Occurs when there are more than 20/30 players, when there are many players.

I already put plugin to remove the limit of packets.

I am using two VPS:

A (Public IP) (OVH) where the proxy is (I used ovh to get the antiddos).
B (Private IP) (Contabo) where pocketmine servers are (downstream).

**Comment by Alemiz112** [comment]
Hello, can you provide more details about your setup? What is downstream software that you use?

**Comment by xxFLORII** [comment]
his downstream software is PocketMine

Alemiz ***@***.***> schrieb am Sa., 5. Feb. 2022, 18:10:

**Comment by ImHammer** [comment]
It's pocketmine

**Comment by sn3akrr** [comment]
I had this same issue a few months ago, but I had around 100-130ish players connecting at once. The downstream server would spam that it's blocking 127.0.0.1 for 300 seconds

**Comment by Crasher508** [comment]
You must set the packetlimit of RaklibInterface to max

**Comment by sn3akrr** [comment]
When this bug happened I did have the packet limit increased.

**Comment by sn3akrr** [comment]
Actually, when I experienced this bug I was increasing the packet limit when my plugins were enabled, instead of on NetworkInterfaceRegisterEvent. Not sure if it happens when you do that correctly

**Comment by ImHammer** [comment]
I have a plugin that puts the packet limit to the maximum (int64), but it still keeps kicking players from the server for *timeout*.
