### ISSUE TITLE
Unable to connect to the server because the version is too low

### ISSUE THREAD

**Issue by BuBaiDeMan** [WaterdogPE/WaterdogPE#157]
I can't log in to my server using waterdogpe. The error on the console is as follows: 

[/120.227.148.94:1734] <-> Upstream has disconnected due to incompatible protocol (protocol=486)

When logging in to the server in the game, it displays: unable to connect, expired server. But my minecraft uses the latest version 1.8.10, and nukkit has also been updated to the latest version. How can I solve this problem? Sorry, my English is not good, so I used google translate.

**Comment by Alemiz112** [comment]
I can not reproduce it now, closing.
