### ISSUE TITLE
fix Login timeout when using 1.18.10

### ISSUE THREAD

**Issue by LadinoXx** [WaterdogPE/WaterdogPE#158]
Fix login timeout and server overload in version 1.18.10 (PM4)!

_Enviado do meu SM-M205M usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xxFLORII** [comment]
![image](https://user-images.githubusercontent.com/38558911/153713982-4fd89b86-e4f0-4cc5-a35e-494a4f254592.png)
for me it's working without timeout and server overload

**Comment by SafiraaCute** [comment]
> ![image](https://user-images.githubusercontent.com/38558911/153713982-4fd89b86-e4f0-4cc5-a35e-494a4f254592.png) for me it's working without timeout and server overload

Maybe it's work on localhost

**Comment by xxFLORII** [comment]
i've tested it on 2 servers, VPS-1 proxy and VPS-2 pocketmine + only localhost
