### ISSUE TITLE
A task raised an exception. Task: com.nukkitx.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$400/0x00000008011add80@7594c028

### ISSUE THREAD

**Issue by Ootmnt150oO** [WaterdogPE/WaterdogPE#160]
![image](https://user-images.githubusercontent.com/60053027/154792530-acc5641d-9711-4407-8130-31f7f047e5c6.png)
![image](https://user-images.githubusercontent.com/60053027/154792533-09950e31-9686-4fd8-9402-b4cb7e5ffafe.png)

**Comment by Alemiz112** [comment]
There isn't method `getServer()` in `ProxiedPlayer` class. You will want to use `player.getServerInfo()` instead. Also you might want to set version of WDPE dependency in your maven/gradle config to be `1.1.6`.

**Comment by Alemiz112** [comment]
Hi, just out of curiosity, what was the issue since you closed this?
