### ISSUE TITLE
downstream server do not receive PlayerAuthInputPacket 0x90

### ISSUE THREAD

**Issue by Crasher508** [WaterdogPE/WaterdogPE#164]
When I join my PocketMine-MP 4.2.2 downstream server over WaterdogPE Proxy, the PocketMine-MP Server do not receive PlayerAuthInput packets (id 0x90). The hole movement of player was broken caused be this issue, can you please send help?

Issue is only happen on join over WaterdogPE Proxy
(sorry for second issue)

**Comment by Crasher508** [comment]
usefull https://wiki.vg/Bedrock_Protocol#Player_Auth_Input idk., issue in StartGamePacket?

**Comment by Crasher508** [comment]
Idea: older Versions of PocketMine-MP send PlayerMovementType legacy (0), on transfer to a newer server proxy do not send the movementtype of new downstream server (example MovementType 1 (Server Auth)) to client

**Comment by Alemiz112** [comment]
Proxy does not modify anything movement related in StartGamePacket. If one of your servers expect to be using PlayerAuthInput packet while other uses PlayerMovePacket than it won't work. Game simply will send the packet based on the movement type from the StartGamePacket of the first server that it joins.

**Comment by Crasher508** [comment]
That means, that I can not use an older version of PocketMine-MP and a uptodate in one network (since 9th December 2021 they use PlayerInputPacket). There is no way to fix, I must aimple update all downstream server :)
