### ISSUE TITLE
ResourcePacks 

### ISSUE THREAD

**Issue by ItsToxicGG** [WaterdogPE/WaterdogPE#165]
How do you set a resource pack in waterdogpe server?
i have put my resource pack in packs folder, enable_packs is enabled
and yes the file is not a zip or mcpack just an folder but still not loading when i put on the server it says "loading 0 packs"

**Comment by ItsToxicGG** [comment]
> How do you set a resource pack in waterdogpe server? i have put my resource pack in packs folder, enable_packs is enabled and yes the file is not a zip or mcpack just an folder but still not loading when i put on the server it says "loading 0 packs"

**Comment by Alemiz112** [comment]
It has to be ZIP file which has the resource pack contents.

**Comment by ItsToxicGG** [comment]
oh ok thanks .

**Comment by ItsToxicGG** [comment]
12:34:14 [ERROR] Resource pack manifest.json is invalid or was not found in DxResources.zip
 
 ???

**Comment by Alemiz112** [comment]
As the message says there is not `manifest.json` and probably rest of the pack inside your zip. You have rather zipped the pack folder than pack content.

**Comment by xxAROX** [comment]
@Alemiz112, can you implement a folder loader that zip the pack async while startup with events on load that includes the packs as classes etc?

**Comment by TobiasGrether** [comment]
Can you elaborate on that idea? @xxAROX
