### ISSUE TITLE
Packet processing error / bad packet

### ISSUE THREAD

**Issue by AxelFeL** [WaterdogPE/WaterdogPE#174]
Please fix bad packet / packet processing error in wdpe 1.1.6 pm4 1.18.30

**Comment by sn3akrr** [comment]
I experience this issue occasionally too

**Comment by AxelFeL** [comment]
I think it's because of pmmp api 4

**Comment by TobiasGrether** [comment]
Packet Processing Errors are caused by you having enabled login_extras, and PM4 not allowing other properties in the Login data.

**Comment by xxAROX** [comment]
> Please fix bad packet / packet processing error in wdpe 1.1.6 pm4 1.18.30

try this [plugin](https://github.com/xxAROX/WaterdogPE-LoginExtras-Fix/releases/download/latest/WD_LoginDataFix.phar), that should fix the login_extras

**Comment by AxelFeL** [comment]
> > Please fix bad packet / packet processing error in wdpe 1.1.6 pm4 1.18.30
> 
> try this [plugin](https://github.com/xxAROX/WaterdogPE-LoginExtras-Fix/releases/download/latest/WD_LoginDataFix.phar), that should fix the login_extras

Thx

**Comment by Crasher508** [comment]
i have disabled login_extra, player will kicked sometimes caused by bad packet

**Comment by Crasher508** [comment]
Yes, i have a /rename Command with this all players can change the name of a item, but the bad packet kick don't came on every join
