### ISSUE TITLE
Timeout login

### ISSUE THREAD

**Issue by LadinoXx** [WaterdogPE/WaterdogPE#178]
I'm having a login timeout issue when the player joins the server, but the stargate is connecting normally.  I have my firewall turned off (the ip and port are right).

![](https://media.discordapp.net/attachments/767331674245431306/981970922342858823/Screenshot_20220602-141854_Minecraft.png)

_Enviado do meu SM-M205M usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by TobiasGrether** [comment]
Please check out our documentation on this [here](https://docs.waterdog.dev/link/25#bkmrk-java.util.concurrent).
