### ISSUE TITLE
Bug when using the shield

### ISSUE THREAD

**Issue by celishere** [WaterdogPE/WaterdogPE#180]
Describe the bug
The bug manifests itself on the latest version of Waterdog, using server software from NetherGames.

It is necessary to take a shield in hand, then to use the shield, the player must sit down to send the generic flag to the client.

After that, the client begins to think that the player is floating, and by holding the space bar, the player can fly up (without releasing the shift button)

Code
`$player->setGenericFlag(Entity::DATA_FLAG_BLOCKING, $player->isSneaking());`

Video
https://youtu.be/iCihG3_Jses

**Comment by Alemiz112** [comment]
Hi, please have a look on similar issue: #123

**Comment by celishere** [comment]
> Hi, please have a look on similar issue: #123

Thank you!
