### ISSUE TITLE
Bug: Command is not showning

### ISSUE THREAD

**Issue by FlxiBoy1313** [WaterdogPE/WaterdogPE#187]
Hey,

I wanted to register a command, but it is not displayed. However, when I add an alias, only the alias is shown to me.

Why is this so?

Code :
```java
// onEnable
getProxy().getCommandMap().registerCommand(new HubCommand());

// HubCommand
public class HubCommand extends Command {

    public HubCommand() {
        super("hub", CommandSettings.builder()
                .setDescription("Return to the lobby")
                .setAliases(new String[]{"lobby"})
                .build());
    }

    @Override
    public boolean onExecute(CommandSender sender, String s, String[] strings) {
        //
        return true;
    }
} 
```

**Comment by FlxiBoy1313** [comment]
So lobby is displayed to me, but hub not

**Comment by irrld** [comment]
This issue has been resolved with https://github.com/WaterdogPE/WaterdogPE/commit/bdd56b95d1ac36d2e420de0fbca0e817dca587b2 commit but its not included with the latest release, you can compile the lastest commit from master branch until the release.

**Comment by FlxiBoy1313** [comment]
Okay thank you very much. I will test it right away

**Comment by FlxiBoy1313** [comment]
Thanks, this is working.
