### ISSUE TITLE
Error Encrypted Packet 604

### ISSUE THREAD

**Issue by nandoferlin1273** [WaterdogPE/WaterdogPE#188]
When i join server with Waterdog it's normal but shortly after i'm in server, the console my server spammed error Encrypted Packet 604 has invalid checksum. Here proof error. The error making my server and proxy crashed. Please fix this

My server version: 1.19
Server type: pocketmine EskoBE 1.19
Waterdog version: 1.1.8

![Polish_20220628_235730879](https://user-images.githubusercontent.com/93959442/176372299-ca08520f-4d97-4e08-8fc0-349c34d536b1.jpg)

**Comment by TobiasGrether** [comment]
What exactly is "pocketmine EskoBE"?

**Comment by Alemiz112** [comment]
You should disable encryption in pocketmine and the issue should solve itself.
