### ISSUE TITLE
Feature: PermissionManager

### ISSUE THREAD

**Issue by FlxiBoy1313** [WaterdogPE/WaterdogPE#189]
Hey,
A function to fetch all permissions that WaterdogPE has registered. 

Could look like this:
```java
getProxy().getPermissionManager().getPermissions();
```

**Comment by TobiasGrether** [comment]
You do not register permissions to any central handler, that is up to the individual plugins to implement - for example through a permission manager. The entire Permission API is only really available through the `ProxiedPlayer` class, therefore this would go against our API design. 
I also don't see any reasonable use case for this kind of API, maybe you can provide one?
