### ISSUE TITLE
NukkitPetterM1Version?

### ISSUE THREAD

**Issue by candrawardana** [WaterdogPE/WaterdogPE#203]
sorry for the spam earlier, it's accident because of recently github is blocked in my country

this version of nukkit allow multiversion up to bedrock 1.2, are waterdogPe support older protocol like bungeecord do? because not only this, PocketMine also has multiversion plugins

**Comment by Alemiz112** [comment]
Hi, yes WDPE supports all Minecraft: Bedrock versions starting with 1.8.

**Comment by candrawardana** [comment]
beta addons can be?
