### ISSUE TITLE
ToastRequestPacket missing at BedrockCodec527 

### ISSUE THREAD

**Issue by Crasher508** [WaterdogPE/WaterdogPE#204]
exception:
2022-08-05 13:14:35.570 [RakNet Listener - #15] ERROR - An exception occurred in RakNet Client, address=/0.0.0.0:0
java.lang.IllegalArgumentException: Packet ID for com.nukkitx.protocol.bedrock.packet.ToastRequestPacket does not exist.
    at com.nukkitx.protocol.bedrock.BedrockPacketCodec.getId(BedrockPacketCodec.java:116) ~[Waterdog.jar:?]

code:
ToastRequestPacket packet = new ToastRequestPacket();
packet.setTitle("title");
packet.setContent("content");
proxiedPlayer.sendPacket(packet);

missing register ToastRequestSerializer_v527 at BedrockCodec527.java

**Comment by DavyCraft648** [comment]
https://github.com/WaterdogPE/WaterdogPE/issues/186#issuecomment-1170454473

**Comment by Crasher508** [comment]
Oh ok sorry, thank you
