### ISSUE TITLE
Some texturepacs are not loaded correctly

### ISSUE THREAD

**Issue by SlidexDE** [WaterdogPE/WaterdogPE#205]
We have the problem that **not all texture packs are loaded** correctly. I was despairing yesterday that I did not have the **Hive Scoreboard UI**. Just now I tested it on a **normal PMMP server** and noticed that **it works fine**.

**Comment by TobiasGrether** [comment]
You're not really providing us with any information here. 

1. Why do you say they are not loaded correctly
2. How did you add those resource packs and how are they structured
3. Are there any errors or logs in the console

**Comment by SlidexDE** [comment]
No, it was actually always "loaded successfully". But now it works, häää xDDDD
