### ISSUE TITLE
Command arguments are not `quote-aware`.

### ISSUE THREAD

**Issue by Cosmic5173** [WaterdogPE/WaterdogPE#206]
Command argument parsing does not take in account arguments wrapped in quotes.

Examples:
- `give "steve jobs" apple` -> ['give', 'steve jobs', 'apple']
- `say "This is a \"string containing quotes\""` -> ['say', 'This is a "string containing quotes"']

Instead, the server breaks up each argument into spaces disregarding the quotes.

**Comment by Alemiz112** [comment]
This is something you can implement as part of command handling. There may be cases, where people will prefer not to handle `quote-aware` arguments, and it will be waste of resources to convert back to original args.

**Comment by KCodeYT** [comment]
But this could be changed with an option in the command settings I guess, `CommandSettings#setQuoteAware(bool)` / `CommandSettings#setQuotingEnabled(bool)`. By default this would be false, but if its true then waterdog parses those quotes so not every plugin needs to implement its own method for doing so.

**Comment by TobiasGrether** [comment]
Hmm this sounds like something I could do in the next few days
