### ISSUE TITLE
Inflation Error when joining servers

### ISSUE THREAD

**Issue by xxFLORII** [WaterdogPE/WaterdogPE#209]
Hello,

sometimes when players try to join/when trying to transfer a player to another server an error occurs. This error occurs only after a certain time, but I have no idea what could be the reason.

Link to the log: https://paste.ee/p/VEr8Z

**Comment by TobiasGrether** [comment]
What server software are you using and have you confirmed this without any plugins on your downstream server?

**Comment by xxFLORII** [comment]
It has occured with PocketMine. We‘ve tested it only with plugins.

But this workaround seems to have helped: 
https://github.com/GeyserMC/Geyser/issues/2861

**Comment by TobiasGrether** [comment]
Are there any steps to reproduce this issue? Since I'm not able to reproduce the issue, some exact reproduction steps would be good

**Comment by xxFLORII** [comment]
Unfortunately, I can't say exactly, because the error only occurred with a friend and not with myself. The error occurred but mostly as far as I know when players have transferred to different servers.

**Comment by xxFLORII** [comment]
but ig it‘s related to this issue too
https://github.com/GeyserMC/Geyser/issues/2694

**Comment by TobiasGrether** [comment]
> but ig it‘s related to this issue too [GeyserMC/Geyser#2694](https://github.com/GeyserMC/Geyser/issues/2694)

Please update your Java version to a newer one, that should potentially fix the issue. (From https://github.com/GeyserMC/Geyser/issues/2861).

Also next time, please try to provide more information in the issue description.
