### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by Rakilem** [WaterdogPE/WaterdogPE#213]
the command /server
it does not work

**Comment by xxFLORII** [comment]
it‘s working for me fine

**Comment by Rakilem** [comment]
I have version 1.19.20 of minecraft
W.D. 1.1.10
NukkitX Software

**Comment by xxFLORII** [comment]
Are you getting any error messages when running the command? And please make sure that you have the permissions to execute this command.

**Comment by Rakilem** [comment]
I don't get any errors, and the permissions are already set
when I use /server survival
it shows that I change the server but no
I'm still in the lobby

**Comment by irapda** [comment]
Unable to transfer / enter the server of nukkitx

**Comment by irapda** [comment]
https://github.com/CloudburstMC/Nukkit/issues/2035
