### ISSUE TITLE
Players don't despawn

### ISSUE THREAD

**Issue by xxFLORII** [WaterdogPE/WaterdogPE#214]
When players leave the game/server, some players don't despawn.

![image](https://user-images.githubusercontent.com/38558911/184391418-0d36dcdd-8a91-4732-8bbd-0bdc1c8180d7.png)

**Comment by DavyCraft648** [comment]
are you using pmmp?
it happens when you teleport a player in DisconectEvent since https://github.com/pmmp/PocketMine-MP/commit/d1dfbd95e2bc01e63d252fe077f2906ca6977005

**Comment by xxFLORII** [comment]
ah okay, thank you. I didn't know that.
