### ISSUE TITLE
Unable to transfer / enter the server of nukkitx

### ISSUE THREAD

**Issue by irapda** [WaterdogPE/WaterdogPE#217]
Unable to transfer / enter the server of nukkitx

**Comment by irapda** [comment]
https://github.com/CloudburstMC/Nukkit/issues/2035

**Comment by Josscoder** [comment]
the same thing is happening to me

**Comment by Alemiz112** [comment]
Hi, make sure you are using both latest Nukkit build. It should be fixed there. (https://github.com/CloudburstMC/Nukkit/commit/90ffdb64c3255b62d1571e36692f7f786d8f2766)

**Comment by Josscoder** [comment]
it works for me, thank you very much
