### ISSUE TITLE
Unable to inflate buffer data

### ISSUE THREAD

**Issue by r3pt1s** [WaterdogPE/WaterdogPE#230]
In Java 11 i added this 2 jvm arguments `-XX:+UnlockDiagnosticVMOptions` and `-XX:-UseAESCTRIntrinsics` and it worked but since waterdogpe using java 17 the arguments doesn't fix it. 
![image](https://user-images.githubusercontent.com/54471820/192095715-70725191-73b5-455f-99e3-ec8dfbfc26fe.png)

**Comment by r3pt1s** [comment]
Oh bruh im dumb, i didn't had the waterdogpe version for 1.19.30 i only had the version for 1.19.21 im sorry.
But the error throws when you join with a higher version

**Comment by Alemiz112** [comment]
Hi, with Java 17 you need to add `-XX:+UnlockExperimentalVMOptions` to enable experimental options.
