### ISSUE TITLE
[BUG]: Can't transfer players with spaces

### ISSUE THREAD

**Issue by supercrafter333** [WaterdogPE/WaterdogPE#237]
I've tryed to transfer a player to antother server with the "server"-command but WDPE said that the player cannot be found but the player was online. I also tryed to transfer a player without spaces on another server and it worked well.
I tryed this: `/server Test "a player with spaces"` (DIDN'T WORKED)
And this: `/server Test testPlayer` (WORKED)

**Comment by DavyCraft648** [comment]
https://github.com/WaterdogPE/WaterdogPE/issues/206 ?

**Comment by TobiasGrether** [comment]
This should be fixed in #206, are you sure you are running the latest release?

**Comment by TobiasGrether** [comment]
Closed due to inactivity.
