### ISSUE TITLE
Security is not clear

### ISSUE THREAD

**Issue by xerenahmed** [WaterdogPE/WaterdogPE#239]
How to be sure that players connect using our Waterdog proxy server?
There are fields like Waterdog_IP and Waterdog_XUID but a rogue proxy server can easily set these fields.
If the user should implement security (maybe with a plugin), they must notify about that.

**Comment by TobiasGrether** [comment]
These login data extensions are largely discouraged and if there is an easier mainstream alternative for it then we are going to remove them iirc. You should not rely on this data to authenticate players. 
Ideally, your firewall configuration will prohibit any traffic to reach the game server except for the traffic that is originating from the proxy.
