### ISSUE TITLE
BUG: Bstats thread is not shutting down, causing shutdown hang

### ISSUE THREAD

**Issue by TobiasGrether** [WaterdogPE/WaterdogPE#241]
When the shutdown method is invoked, all components of the Proxy are shut down.

The shutdown is based on the assumption that afterwards there are no threads left (because all are closed correctly by proxy & plugins).
Since bstats currently does not provide a sufficient way to shut down it's `ScheduledThreadPool`, the proxy might hang for a randomized amount of time before shutting down (due to the random element in the Bstats scheduler interval).

Ideally, bstats should expose a shutdown method which allows external code to shutdown the pool. This is currently in discussion with the bstats team.

Resolution:
A temporary resolution would be to disable anonymous statistics for the time being. We do not recommend doing that, since the issue should be resolved fairly soon, however if you feel like this is definitely required, then you can mitigate the issue by setting the statistics enabled toggle in the `config.yml` to `false`.

**Comment by Alemiz112** [comment]
Not because of this, but I made in b58d481 a shutdown method to call `System.exit()`, which should also "fix" this issue.

**Comment by TobiasGrether** [comment]
A proper solution has been implemented on the bstats-side and I will PR a proper fix for this issue in the coming days.

https://github.com/Bastian/bstats-metrics/commit/a2570ef0db3c1f4cbd645bd7ba328c253f7abc67

**Comment by TobiasGrether** [comment]
Just following up, this should be fixed already since 7dbee860263b27cf9d7eaadff08558ef546800ff
