### ISSUE TITLE
Unsupported / Missing Packet

### ISSUE THREAD

**Issue by Buddelbubi** [WaterdogPE/WaterdogPE#250]
**Describe the bug**
WaterDogPE does not support UpdatePlayerGameTypePacket.
SetPlayerGameTypePacket is abandoned and should not be used anymore. 
Some serversoftware (like PowerNukkitX) does not even support this packet anymore.
This results in gamebreaking behaviour.

**To Reproduce**
1. Join server (PNX for example)
2. Change your gamemode
3. See yourself in the same gamemode as before.

**Expected behavior**
Change the gamemode on clientside

**Screenshots**
https://youtu.be/ixf4MbtrGzE

**Platform Information:**
 - Game Platform: Windows
 - Game (Client) Version: 1.19.50
 - Server OS: Ubuntu
 - Java Version: Java 18
 - Server Deployment Method: CloudNet

**Comment by Alemiz112** [comment]
Hi, this will be fixed in #253.

**Comment by Alemiz112** [comment]
Closing as this was completed.
