### ISSUE TITLE
[BUG] java.util.concurrent.TimeoutException

### ISSUE THREAD

**Issue by Pigeon2333** [WaterdogPE/WaterdogPE#252]
**Describe the bug**
When a player tries to connect to the lobby server, the connection times out with a probability and the following error is displayed:
Disconnected with: Connection to lobby1 failed: java.util.concurrent.TimeoutException

**To Reproduce**
1. Join server
2. See error（probabilistically）

**Expected behavior**
Players should be properly connected to downstream servers.

**Screenshots**
![image](https://user-images.githubusercontent.com/68182691/209645219-de843873-a9f0-498c-a4a3-c9535156ae48.png)

**Platform Information:**
wdinfo:
Running WaterdogPE version 1.2.3!
Build Version: release
Latest Protocol: 560
Branch:  ad8fa0d0c8fc549ac7a44591d1cb5b77581ecd70 CommitId: ad8fa0d
Author: WaterdogTEAM
Developer Mode: enabled

**Additional context**
None.

**Comment by Pigeon2333** [comment]
Supplement: I've been refer to the document(https://docs.waterdog.dev/link/25#bkmrk-java.util.concurrent), I confirm my address configuration no problem, because when the mistakes, there are other players can join the server properly

**Comment by TobiasGrether** [comment]
Hello there,

can you test this with the current release and can you share the logs with us while having the debug mode enabled?
