### ISSUE TITLE
Feature Request: Disable transfer screen

### ISSUE THREAD

**Issue by Hexatronic01** [WaterdogPE/WaterdogPE#254]
Add an option to disable the screen when transfering, in lifeboat when you transfer to a different server it dosent show anything it just changes the visual chunks and this is very good since it dosent bug out all of the time.

**Comment by Alemiz112** [comment]
Hi, this is already implemented in #253.

**Comment by jameshackerbond** [comment]
I wasnt talking about the MCPETransferPacket it was the dimension change packet I would request if you can implement an option to turn that off so the dimension change packet does not show up, so then it will just look like the nemisys transfer.

**Comment by Alemiz112** [comment]
Yes, I know. As already mentioned, it is implemented in #253.

**Comment by Alemiz112** [comment]
Closing as this has been now implemented.

**Comment by Alemiz112** [comment]
There is [transferScreenAllowed](https://github.com/WaterdogPE/WaterdogPE/blob/master/src/main/java/dev/waterdog/waterdogpe/event/defaults/ServerTransferEvent.java#L29) property in ServerTransferEvent, which can be used to toggle transfer screen on or off.
