### ISSUE TITLE
An error has occurred in the runtime console

### ISSUE THREAD

**Issue by Emotionalyear** [WaterdogPE/WaterdogPE#255]
An error has occurred in the runtime console: 
Unknown channel option 'IP_DONTFRAG' for channel '[id: 0xe6f344f8]' 
![image](https://user-images.githubusercontent.com/89445415/211954058-16edf18a-e282-4e95-9429-2d96db07cf37.png)

At the same time, this error will also be reported when transferring across servers, I deleted the configuration file and then restarted it still did not help, what is the problem, thank you

**Comment by Alemiz112** [comment]
Hi, as the log level tells, it is just a warning and does not affect any proxy functionality. It can be ignored for now. Should be fixed in #253 however.
