### ISSUE TITLE
[BUG] Downstream server stops responding

### ISSUE THREAD

**Issue by Ree-jp** [WaterdogPE/WaterdogPE#257]
**Describe the bug**
Joining a server with the default skin and transferring to another server causes the server to become unresponsive
When this happens, you will not be able to enter commands, destroy/place blocks, use items, etc.
Only the commands that are set in the proxy will work.
Also, when I leave and rejoin, the same thing happens on the first server I connect to.
Restarting WaterdogPE restores normal operation on the first server I connect to.

**To Reproduce**
1. Join server
2. Move to another server
3. Downstream server stops responding

**Expected behavior**

**Screenshots**

**Platform Information:**
 - Game Platform: Windows11, IPad
 - Game (Client) Version v1.19.62, v1.19.60
 - Server OS linux
 - Java Version Java 17
 - Server Deployment Method Pterodactyl
 - Downstream PocketMine-MP 4

**Additional context**
Similar to #256, but in my case it didn't happen on andorid, but on windows!
Also, someone using an IPad reported the same problem.

**Comment by supercrafter333** [comment]
Update your client and your servers to 1.19.62. This bug was caused by a misstake of Mojang.

**Comment by Ree-jp** [comment]
thank you
i will check it when i get home

**Comment by Ree-jp** [comment]
cured
thank you
