### ISSUE TITLE
Not load Bug

### ISSUE THREAD

**Issue by Ardaa001** [WaterdogPE/WaterdogPE#258]
Do the waterdog quick transfer also help 3/2 of the players teleported from the hub to SkyBlock the game does not load full, can not open the inventory and can not break the block.

**Comment by TobiasGrether** [comment]
Hello,

can you provide some more information? A video showing the gameplay when the issue occurs would be very useful. 
Some logs would also be useful.

**Comment by TobiasGrether** [comment]
Closed due to inactivity.
