### ISSUE TITLE
Player List & Xbox Live

### ISSUE THREAD

**Issue by GouDan888** [WaterdogPE/WaterdogPE#262]
![(OLBWK3CHXZWU$(E@@JTNB1](https://user-images.githubusercontent.com/49330438/230335971-943c92a9-1edf-4f17-8d10-d340ae688591.png)
The avatar has turned black and cannot be clicked。

![}JJS%{VKQDXV%}Q%)B($}WV](https://user-images.githubusercontent.com/49330438/230336161-6b1f7d4b-c01e-40cc-bb2a-26e8cd2a129e.png)
In NetherGames, normal display。

**Comment by TobiasGrether** [comment]
You have to make sure that your downstream server software sends the xbox ID of the player with the PlayerListEntry although the server is in offline mode
