### ISSUE TITLE
[BUG] FOV bug

### ISSUE THREAD

**Issue by xxFLORII** [WaterdogPE/WaterdogPE#270]
**Describe the bug**
When you are in spectator mode and change the server, the FOV changes.

**To Reproduce**
1. Join a sub server
2. Go into the gamemode Spectator
3. Switch the server

**Expected behavior**
The FOV should not change when switching servers

**Screenshots**
https://youtu.be/lw4-ivdSv70

**Platform Information:**
 - Game Platform: Windows 11, iOS
 - Game (Client) Version [e.g. v1.19.80]
 - Server OS Debian 11
 - Java Version 17
 - Server software: NukkitX (https://github.com/CloudburstMC/Nukkit/commit/b836d4d5d4baef56f3c8e5af2baa620d7ae6a88e)

**Comment by xxFLORII** [comment]
Side info: This also occurs with 2 completely rebuilt Nukkit servers without plugins.

**Comment by xxFLORII** [comment]
It seems to be related to these commit: https://github.com/CloudburstMC/Nukkit/commit/150ee4ff5581f4a79f26897dd5aab11bcded071d

**Comment by Alemiz112** [comment]
The FOV is changed by client abilities. When using *fake spectator* player is technically still in creative/survival so it still expects abilities on `BASE` layer, which also defines player FOV.

For *fake spectator* the abilities sent on `SPECTATOR` layer should be `FLYING, NO_CLIP` + `BASE` layer as in all other game modes. (spectator layer should be the second one in the abilities list)

Adding to that, WDPE does not track player abilities and it is up to the server to send them each time when joining.

**Comment by xxFLORII** [comment]
Okay, but why does it work with PocketMine, or do they do something different?

**Comment by Alemiz112** [comment]
Because PocketMine sends abilities basically as I described.

**Comment by xxFLORII** [comment]
I thought Nukkit did the same, but then apparently not. Is there perhaps a way to fix this, if so, what exactly would I have to change? Unfortunately, I do not know so well with it.
