### ISSUE TITLE
[BUG] Already connected causes player timeout

### ISSUE THREAD

**Issue by ShockedPlot7560** [WaterdogPE/WaterdogPE#273]
**Describe the bug**
With 500/600ms of simulated ping, we obtain the capture below.
![image](https://github.com/WaterdogPE/WaterdogPE/assets/66992287/3037e3e1-8d92-40f0-ad3b-6b8f352c3e63)
The packet returned by waterdog: already connected, causes minecraft to load continuously until a client timeout.

**To Reproduce**
1. Simulate 500/600ms of ping
2. Login
3. See error  

Reproducible on Nether game

**Expected behavior**
The packet is not returned, or does not cause the server to load endlessly

**Platform Information:**
 - Game Platform: Windows 10
 - Game (Client) Version: >1.19
 - Server OS: Ubuntu
 - Java Version: 17
 - Server Deployment Method: Docker

**Comment by Alemiz112** [comment]
Hi, this commit https://github.com/CloudburstMC/Network/commit/80181f2ff6c62172ce6cacdb09517896776ce0c6 in RakNet library should fix the issues.
The latest GitHub build should include those changes.

**Comment by ShockedPlot7560** [comment]
> Hi, this commit [CloudburstMC/Network@80181f2](https://github.com/CloudburstMC/Network/commit/80181f2ff6c62172ce6cacdb09517896776ce0c6) in RakNet library should fix the issues. The latest GitHub build should include those changes.

Thanks for the reply.
However we use a custom image from the Jar found on the jenkins.

**Comment by Alemiz112** [comment]
Jenkins builds are outdated few months already. I would suggest to use jars from GitHub releases - pre-release jar is a replacement to Jenkins snapshot build.

**Comment by ShockedPlot7560** [comment]
Resolved ✅
