### ISSUE TITLE
Release v2 to docker-hub

### ISSUE THREAD

**Issue by xxAROX** [WaterdogPE/WaterdogPE#278]

**Comment by TobiasGrether** [comment]
Hmm yeah the docker publishing in itself appears to be broken, will take a look

**Comment by xxAROX** [comment]
Thanks 👍

**Comment by xxAROX** [comment]
Ahh okay, maybe notice on dockerhub to avoid issues like this

**Comment by TobiasGrether** [comment]
> Ahh okay, maybe notice on dockerhub to avoid issues like this

Yeah I didn't actually know about that because it was still in discussion iirc, but I'll fix that rq

**Comment by TobiasGrether** [comment]
Added a warning
