### ISSUE TITLE
Destination server info

### ISSUE THREAD

**Issue by chelminski** [WaterdogPE/WaterdogPE#290]
**Is your feature request related to a problem? Please describe.**
It solves many problems, e.g. when we have a proxy connected to another proxy (don't ask ;) ), we use non-standard software or allow access to the server via different paths (including offline). I understand that it may seem trivial, but it is extremely important to me.

**Describe the solution you'd like**
I would like to add the ability for things like ping, motd, as well as the current player count to be fetched from the target server.

**Additional context**
Something like that

# Relay the MOTD from the remote server
passthrough-motd: false
# Relay the protocol name (e.g. nukkit, paper etc) - only really useful when using a custom protocol name!
# This will also show up on sites like MCSrvStatus. <mcsrvstat.us>
passthrough-protocol-name: false
# Relay the player count and max players from the remote server to Bedrock players.
passthrough-player-counts: true

**Comment by TobiasGrether** [comment]
You should be able to implement this yourself quite easily by polling servers yourself and then updating the QueryEvent values and player counts according to the results of your latest poll. I think this should be left to the developer to implement, that is what the Plugin API is for. 

CC @Alemiz112

**Comment by Alemiz112** [comment]
Hi, I as far as I am concerned, this is not something that bedrock protocol is capable of. Bedrock does not support SRV records and RakNet ping does not contain information about which server a player is trying to reach/using what domain name was server resolved.

**Comment by TobiasGrether** [comment]
I suppose you could ping the default downstream server that your join handler returns to connect to, but thats about it. Stuff like specific domain names aren't joinable just for MOTDs. If you have any question about what I mean, feel free to ask in the discussions tab or on our discord server.
