### ISSUE TITLE
Multi protocol support

### ISSUE THREAD

**Issue by chelminski** [WaterdogPE/WaterdogPE#291]
**Is your feature request related to a problem? Please describe.**
It solves the problem where we don't want to use the latest version of minecraft as a game server.

**Describe the solution you'd like**
Allow newer client versions to connect to older server versions

**Additional context**
Something like how the [ViaVersion plugin](https://www.spigotmc.org/resources/viaversion.19254/) works for java servers.

**Comment by Alemiz112** [comment]
Hi, WDPE supports clients with multiple versions. However it is not and shouldn't be a responsibility of the proxy to translate protocol for older versions. However, this is a good idea for a plugin.
