### ISSUE TITLE
[BUG] This is a bug!

### ISSUE THREAD

**Issue by serrpr** [WaterdogPE/WaterdogPE#303]
Hello, WaterdogPE is not working for me, how do I fix it?
![image](https://github.com/WaterdogPE/WaterdogPE/assets/167159939/497f3662-2f3b-4330-8d43-8b6f811c0879)

**Comment by serrpr** [comment]
Hello @Alemiz112 , can you help me? please

**Comment by Josscoder** [comment]
I think it's because the client or server is outdated

**Comment by serrpr** [comment]
> I think it's because the client or server is outdated

It is the latest version of minecraft bedrock

**Comment by serrpr** [comment]
Hey @Josscoder Any comments that can help me?

**Comment by ClydeplayzYT590** [comment]
> > I think it's because the client or server is outdated
> 
> It is the latest version of minecraft bedrock

then your server is outdated, try using this jar from the latest release:

https://github.com/WaterdogPE/WaterdogPE/releases/download/v2.0.2/Waterdog.jar

**Comment by Jayseba04** [comment]
> > > I think it's because the client or server is outdated
> > 
> > 
> > It is the latest version of minecraft bedrock
> 
> then your server is outdated, try using this jar from the latest release:
> 
> https://github.com/WaterdogPE/WaterdogPE/releases/download/v2.0.2/Waterdog.jar

![image](https://github.com/WaterdogPE/WaterdogPE/assets/118990301/581d3ebb-7258-46f8-bf26-bbfd4ada4431)

https://jenkins.waterdog.dev/job/Waterdog/

**Comment by DavyCraft648** [comment]
@Jayseba04 no, we don't use jenkins anymore
