### ISSUE TITLE
Start servers on-demand

### ISSUE THREAD

**Issue by rartino** [WaterdogPE/WaterdogPE#304]
After setting the software up to proxy connections to a few servers based on `public_address`, I realized that my setup would be even better if I could get WaterdogPE to support spinning up these servers on-demand instead of just proxy to running servers. 

I imagine something like this: the `servers` section of `config.yml` is extended to allow that we for each server can specify a `startup_script`, `shutdown_script` and a `shutdown_timeout` setting.

1. When the first user connects to a server with those settings, the `startup_script` is executed and only after that script finishes the user's connection is proxied to the now running server.

2. After this, WaterdogPE works as usual, proxying additional user's to that server.

3. When the last user disconnect from the server, WaterdogPE waits `shutdown_timeout` seconds, and if no new user connects to the server in that time, it runs the `shutdown_script`.

4. If a user tries to connect to the same server after this, the process starts from '1' again.

I think this may be manageable to implement, given that it mostly involves counting active connections and running external scripts. I may even take a look at the code and see if I can add it myself. Is this something that would fit into WaterdogPE and be merged?

**Comment by belohnung** [comment]
You could implement that in a plugin or use a ready made solution, I don't think this is in scope with WaterdogPE.
An example of a ready made solution, while a little more than what you asked for is [CloudNet](https://github.com/CloudNetService/CloudNet-v3)

**Comment by rartino** [comment]
Thanks, I had actually missed the extent of the plugin support, I'll try that route.

It was the complex nature of CloudNet and other readymade solutions that made me think: maybe I can just get the proxy to spin up java as needed instead.
