### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by GabBiswajit** [WaterdogPE/WaterdogPE#307]
Waiting for 1.20.80...

**Comment by Toper9636** [comment]
WDPE uses [Cloudburst Protocol](https://github.com/CloudburstMC/Protocol), and new version support depends on this library (They are the first to add support for new versions). In order for WDPE to support the new version you just need to update the version of this library (Or maybe not) in `pom.xml` and add one line similar to this commit: [Click here](https://github.com/WaterdogPE/WaterdogPE/commit/d895ce6e545aeecc1fb3d2f6f2e736cd11afd92b)

**Comment by Toper9636** [comment]
There is support for the new version in this thread: https://github.com/WaterdogPE/WaterdogPE/tree/v1.20.80

**Comment by Toper9636** [comment]
![image](https://github.com/WaterdogPE/WaterdogPE/assets/102699826/eb0b8374-ae3c-4780-b107-c0980b4d1bd0)

**Comment by ClydeplayzYT590** [comment]
https://github.com/WaterdogPE/WaterdogPE/actions/runs/8807095226 <- WDPE 1.20.80
