### ISSUE TITLE
The server hub went down, reason: Error whilst deserializing PlayerListPacket(entries=[], action=ADD)

### ISSUE THREAD

**Issue by Odidak1** [WaterdogPE/WaterdogPE#313]
I can't enter the server, something like the following appears:

The server hub went down, reason: Error whilst deserializing PlayerListPacket(entries=[], action=ADD)

Please fix it immediately

**Comment by MLCraftKaiKai** [comment]
Please use custom skin (skin. png), market skin cannot be accessed. :)

**Comment by Odidak1** [comment]
That's enough
