### ISSUE TITLE
[BUG] PlayerDisconnectedEvent sometimes does not get called

### ISSUE THREAD

**Issue by irrld** [WaterdogPE/WaterdogPE#320]
**Describe the bug**
`PlayerDisconnectedEvent` does not get if encryption is enabled and client timeouts before `ClientToServerHandshakePacket` was received. Since `ProxiedPlayer::initPlayer()` is never called, loginCompleted is never set to true, which means `ProxiedPlayer::disconnect(String)` returns without calling the events and doing the cleanup stuff including calling `PlayerDisconnectedEvent` and removing the player from the list.  

**To Reproduce**
1. Enable encryption and debug from WDPE config.yml
2. This happens randomly but easiest way to reproduce is to comment out the `this.finishConnection();` line in `LoginUpstreamHandler::handle(ClientToServerHandshakePacket)`
3. Join the proxy
4. Disable your ethernet device that connects you to the internet immediately. (Timeout from the server, you could also disable your Wi-Fi or unplug your ethernet cable)
5. After 10 seconds, in proxy logs you should see something similar to `Disconnecting RakNet Session (/IP:19132 => /IP:62815) due to TIMED_OUT`
6. Type wdlist to confirm. You'll see `Total online players: 1` but you are not actually in the server. If you log `PlayerDisconnectedEvent` or debug, you'll see that `ProxiedPlayer::disconnect(String)` returns immediately because loginCompleted is false.

**Expected behavior**
At any stage after the player is registered to the proxy (PlayerAuthenticatedEvent completed without getting cancelled), if player disconnects, PlayerDisconnectedEvent should be called and player should be removed from the proxy player list properly.

**Platform Information:**
 - Game Platform: Windows
 - Game (Client) Version: 1.21.20, latest
 - Server OS: MacOS
 - Java Version: Java HotSpot(TM) 64-Bit Server VM (build 17.0.5+9-LTS-191, mixed mode, sharing)
 - WDPE Commit: 4e2b3cd1a3d5e4d3599476fd907b6bd3186783eb on master

**Comment by Alemiz112** [comment]
Should be resolved now.
