### ISSUE TITLE
change package name

### ISSUE THREAD

**Issue by lukeeey** [WaterdogPE/WaterdogPE#33]
The package name should be changed to `dev.waterdog` from `pe.waterdog` as the convention is to use the domain name as the package name.

This should be done ASAP before the software starts getting more popular.

**Comment by TobiasG-DE** [comment]
Agreed, @Alemiz112 will do later if you agree

**Comment by Alemiz112** [comment]
Yeah, sure. The first plan was to get `waterdog.pe` but later we have decided for `waterdog.dev` and somehow forgot to change package name 😄

**Comment by Alemiz112** [comment]
Package name changed in #34
