### ISSUE TITLE
No react on anything after internal server error

### ISSUE THREAD

**Issue by RexZetronYT23** [WaterdogPE/WaterdogPE#40]
**Describe the bug**
If i get a internal server error of a server where i want to connect with wdpe the world doesn't load an i on a fallback server but idk where i'm. I dont can break blocks, i dont can do commands.

**To Reproduce**
1. Write a Plugin with an Internal server error ( without an ; idk) 
2. Transfer to server where the plugin is 
3. Look, you see a error.

**Expected behavior**
I expected that i get a reconnect to my lobby but idk where was then.

**Screenshots**
![Screenshot_2021-02-04-23-51-37-375_com.mojang.minecraftpe.jpg](https://user-images.githubusercontent.com/57451491/106967719-efe47d80-6747-11eb-820e-ab2d0af1dba0.jpg)

**Platform (please complete the following information):**
 - OS: Debian 10
 - Java Version 8
 - Actually WaterdogPE Version.

**Comment by TobiasG-DE** [comment]
When the downstream server crashes, the proxy cannot know that it did, because the server sends us no DisconnectPacket. Therefore the proxy needs to wait for a timeout in the connection. Right now there is no way to fix this behavior, but this behavior is expected.
