### ISSUE TITLE
Downstream switch

### ISSUE THREAD

**Issue by xxAROX** [WaterdogPE/WaterdogPE#52]
**Is your feature request related to a problem? Please describe.**
> Nah, but its annoying.

**Describe the solution you'd like**
> Forms, Titles(ActionBar, Tip, etc.) & Scoreboards will removed on server switch

**Describe alternatives you've considered**
> Caching all forms ids, if player send form -> remove from cache, then send data null (player closed form)

**Comment by Alemiz112** [comment]
Hi, form closing is not implemented in proxy side to save performance by not decoding form packets. If you really require it, it can be done from plugin. There is `dim-change` branch which supports dimension change (forms are closed by client in that case) and is in progress of merge to master.

**Comment by xxAROX** [comment]
ahh okay, the plugin idea sounds great, and whats with clearing Titles & Scoreboards?

**Comment by Alemiz112** [comment]
Scoreboards are cleared by proxy and I dont think not clearing titles is so big problem, but it can be done.

**Comment by xxAROX** [comment]
👌
