### ISSUE TITLE
AvailableCommandsPacket doesn't work correctly.

### ISSUE THREAD

**Issue by alvin0319** [WaterdogPE/WaterdogPE#54]
**Describe the bug**

AvailableCommandsPacket doesn't work correctly.

Without proxy:
![image](https://user-images.githubusercontent.com/32565818/108696547-0a3e9980-7545-11eb-9939-1f85d632de2a.png)

With proxy:
![image](https://user-images.githubusercontent.com/32565818/108696676-378b4780-7545-11eb-8b92-2f5de0fbbb57.png)

**To Reproduce**
1. Join server
2. Enter the command

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Linux, Distribution] Windows 10
 - Java Version:
 ```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.11+1-202102091838)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.11+1-202102091838, mixed mode)
```
 - Version of Waterdog: https://github.com/WaterdogPE/WaterdogPE/commit/7dfeff7deb1bd14946e2028dbccbf6939f82a8e4

**Additional context**

**Please make sure the bug you are reporting hasn't been reported here already. Duplicate issues will be quickly closed.**

**Comment by Alemiz112** [comment]
Hello, thanks for reporting this issue. We are already aware of it and are working on fix. For now disabling `inject_proxy_commands` should fix it.

**Comment by TobiasG-DE** [comment]
With what server software is this an issue?

**Comment by alvin0319** [comment]
I have an issue with PocketMine-MP, as you can see on screenshots.

**Comment by Alemiz112** [comment]
Having `inject_proxy_commands` option enabled should no longer be problem. However you might have some issues as incorrect command parameters due to pocketmine.

**Comment by Alemiz112** [comment]
This issue should be already solved, `inject_proxy_commands` can be enabled and will tolerate unknown command param types.
