### ISSUE TITLE
Bossbar is not displayed 

### ISSUE THREAD

**Issue by WylSmart** [WaterdogPE/WaterdogPE#63]
On other proxies, I have a bossbar displayed in this one, please fix it

**Comment by WylSmart** [comment]
BossBar please fixed

**Comment by Alemiz112** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bossbar doesnt work correctly with WaterdogPE, needs further investigation](https://trello.com/c/6p6t4SeJ/30-bossbar-doesnt-work-correctly-with-waterdogpe-needs-further-investigation)

**Comment by loperd** [comment]
Please provide more details to reproduce this cause

**Comment by sn3akrr** [comment]
Start up two servers with the same world and connect them using the proxy and you should be able to see it on each server when transferring. Connect a third server using a world with a different name and it won't spawn if you try

**Comment by irrld** [comment]
I guess this was fixed in the latest release. Can you close the issue if that was related to this @Alemiz112.
