### ISSUE TITLE
Reload Resource Packs

### ISSUE THREAD

**Issue by xxAROX** [WaterdogPE/WaterdogPE#69]
**Is your feature request related to a problem? Please describe.**
/

**Describe the solution you'd like**
A command to reload all resource packs.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by xxAROX** [comment]
yea, this, but proxy-side whould amazing 😯

**Comment by Alemiz112** [comment]
Changing packs during runtime is not stable enough to be used. Therefore it won't be implemented at current state.

**Comment by xxAROX** [comment]
Okay, whats if you kick all players i mean the command is only for admins?

**Comment by xxAROX** [comment]
@Alemiz112

**Comment by Alemiz112** [comment]
If you are talking about reloading packs and than kicking players to force reapply packs, that is job which should be done by plugin.

**Comment by xxAROX** [comment]
Okay
