### ISSUE TITLE
How do I force players to log in through the proxy?

### ISSUE THREAD

**Issue by ImHammer** [WaterdogPE/WaterdogPE#70]
**Is your feature request related to a problem? Please describe.**
How do I force players to log in through the proxy?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xxAROX** [comment]
```php
/** @var \pocketmine\Player $player */
if ($player->getAddress() !== "127.0.0.1") {
   $player->close("Please join via Proxy!");
}
```

**Comment by xxAROX** [comment]
[Here](https://github.com/WaterdogPE/WaterdogPE/discussions/new) whould be better next time

**Comment by TobiasG-DE** [comment]
Another idea instead of kicking the player, what could lead to confusion, would be to just hard-transfer him to the proxy address using $player->transfer();. Issue marked as solved.
