### ISSUE TITLE
Make a Plugin Website

### ISSUE THREAD

**Issue by Altamash347** [WaterdogPE/WaterdogPE#74]
**Is your feature request related to a problem? Please describe.**
Its very hard to find plugins for WaterDogPE

**Describe the solution you'd like**
I would like a website which will have the plugins made by other people who submitted and approved by WaterdogPE team

**Describe alternatives you've considered**
poggit.pmmp.io

**Additional context**
Make a Plugin website for WaterdogPE

**Comment by Altamash347** [comment]
https://plugins.waterdog.dev/ can be a good domain

**Comment by TobiasG-DE** [comment]
It was already considered by us a lot but I believe right now both Alemiz and me are limited in resources and time

**Comment by EinBexiii** [comment]
Can be closed. https://plugins.waterdog.dev
@TobiasG-DE
