### ISSUE TITLE
Make the proxy have multiversion support.

### ISSUE THREAD

**Issue by MegaTKC** [WaterdogPE/WaterdogPE#84]
Steadfast2 has multiversion support but, waterdog doesn't. Can you please somehow add multiversion support like Steadfast2? Thanks.

**Comment by MegaTKC** [comment]
Somehow I can't label this as an enhancement.

**Comment by Alemiz112** [comment]
WaterdogPE supports all versions since 1.8

**Comment by MegaTKC** [comment]
Oh thanks!
