### ISSUE TITLE
Cant run the Jar

### ISSUE THREAD

**Issue by CrowBaldeYT** [WaterdogPE/WaterdogPE#86]
![Screenshot_20210418_205518](https://user-images.githubusercontent.com/75171427/115157229-71318800-a088-11eb-92ed-c728d8695f63.jpg)

Cant run jar

**Comment by TobiasG-DE** [comment]
Have you tried reading what's written there?

**Comment by Alemiz112** [comment]
You need Java 11 to start WaterdogPE.
