### ISSUE TITLE
[SUGGESTION:] Add setMotd(String $motd)

### ISSUE THREAD

**Issue by supercrafter333** [WaterdogPE/WaterdogPE#88]
Hey,
can you add a setMotd(String) function to the proxy functions, please?

That can be useful for time to time changing MOTD.

**Comment by XKazzuKX** [comment]
You are already able to do this I’m the `ProxyPingEvent`

**Comment by Alemiz112** [comment]
As said above, `ProxyPingEvent/ProxyQueryEvent` is used to set motd.

**Comment by supercrafter333** [comment]
Yes, but that's bad for beginners

**Comment by XKazzuKX** [comment]
> Yes, but that's bad for beginners

Care to elaborate?

**Comment by xxAROX** [comment]
> 
> 
> Yes, but that's bad for beginners

its an event listener thats easy
