### ISSUE TITLE
if you type "@" into the chat

### ISSUE THREAD

**Issue by xxAROX** [WaterdogPE/WaterdogPE#92]
if you type "@" into the chat
![grafik](https://user-images.githubusercontent.com/57589973/117539842-b48a7100-b00c-11eb-8730-7455ecedfdf1.png)

My playername is not in the list

Settings:
- fast transfer(no dimension screen)

**Comment by Alemiz112** [comment]
This isn't most likely proxy issue. I also can not reproduce it when using nukkit as downstream server.

**Comment by xxAROX** [comment]
i use pmmp/altay

**Comment by BlckqFlorian** [comment]
i have the same issue.

**Comment by Alemiz112** [comment]
Okay. So I have tried it with pmmp too. But it still works correctly for me.

**Comment by xxAROX** [comment]
fixed in dimension change screen
