### ISSUE TITLE
MANY PACKETS (DDOS BY PROXY)

### ISSUE THREAD

**Issue by ImHammer** [WaterdogPE/WaterdogPE#94]
1° Erro: The waterdog keeps knocking down many players on the network with the reason * Disconnected from Server *

2° Erro: Besides sending lots of packets to the pocketmine, making it take a long time to process the packets from the same proxy ip, is there any way to fix this?

**Comment by TobiasG-DE** [comment]
No way given to reproduce, didn't follow issue template, no exact description of the issue.
