### ISSUE TITLE
Logged in other location and twice nickname bug

### ISSUE THREAD

**Issue by AlicanCopur** [WaterdogPE/WaterdogPE#95]
When someone join the proxy and downstream, his nickname appears twice in pause menu list.

![image](https://user-images.githubusercontent.com/37244649/118472955-1f752f80-b712-11eb-8698-a4b2fe8c5700.png)

(possibly also related to this) it sometimes kicks people who enter the server because of "logged in other location".

**Comment by xxAROX** [comment]
Already online should be better

**Comment by TobiasG-DE** [comment]
Have you tried this completely without any plugins? And please specify a way to reproduce this

**Comment by Alemiz112** [comment]
I can confirm this bug.
It isnt proxy related. It is nukkit bug where the login sequence completion code is executed twice.

**Comment by Alemiz112** [comment]
> I can confirm this bug.
> It isnt proxy related. It is nukkit bug where the login sequence completion code is executed twice.

It happens because of how async login stuff is implemented there. And with proxy the actual "downstream login" is finished faster than usually which allows this bug to appear.
