### ISSUE TITLE
players get stuck in the dimension screen

### ISSUE THREAD

**Issue by Superzock3003** [WaterdogPE/WaterdogPE#97]
Every time I want to switch an server with a other dimension (nether or end) I will get stuck in this screen:
![Minecraft 24 05 2021 12_26_31](https://user-images.githubusercontent.com/67550519/119335933-4640e200-bc8d-11eb-863b-dacd033b4b2c.png)

I'm using PowerNukkit (https://github.com/Superzock3003/PowerNukkit/actions/runs/869664280) and the master branch (c2c3e13) of waterdogpe

**Comment by TobiasG-DE** [comment]
Could you please provide us with debug logs from your Nukkit and your WaterdogPE server?

**Comment by Superzock3003** [comment]
> Could you please provide us with debug logs from your Nukkit and your WaterdogPE server?

WaterdogPE: 
![Unbenannt](https://user-images.githubusercontent.com/67550519/119341982-bacb4f00-bc94-11eb-9a18-66b72f7fa6a9.PNG)
PoweNukkit: 
![image](https://user-images.githubusercontent.com/67550519/119342300-2a413e80-bc95-11eb-89ed-5f199787cb60.png)
and it keep spamming NAK'ed datagram...

**Comment by Alemiz112** [comment]
Hello,
currently only transfer from overworld to overworld dimension is suppored. All dimensions support is already the thing in my TODO list.

**Comment by Alemiz112** [comment]
Solution implemented in d495ccb, closing.
